### ISSUE TITLE
Add an simple example

### ISSUE THREAD

**Issue by Bk8** [benkuper/juce_timeline#1]
Please could you a add a simple example, explaining how to use these classes please.

**Comment by benkuper** [comment]
Hello,
You can see implementations of thoses classes in the BenTo software : http://github.com/benkuper/BenTo 
Take a look at the Timeline folder.
This module is heavy relying on the juce_organicui module, so you may want to start there :)
I'm sorry that documentation is scarce, I don't have much time to do that and the community is too small for now !

**Comment by Bk8** [comment]
Ok thanks a lot!
